sudo: false
language: node_js
node_js:
- '10'
matrix:
  fast_finish: true
  allow_failures: []
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: QVmBDt527EZtZmdqJhDpU1cgoWFY/dPFh97b1DGYhmOoBPKSdavMhyIq0VQ1FxaFNnoXKTroHweGjvFXxq7TbZhpzFWaARnh4XAD6g/AyUU7vzJmD77dmQjgHKD5kTozJO875eOXk+lK7Qc5/OLAU9dHlSHUmr2LKdFIWcnQqHPtFTBKrLurds3qLdDw4gaLf5J7bsTO4EoHKoNiSmVhpL598SB2HswXq2Eclhv+GCF4Ri5prrdhXdfUzAvUQSRD2cB9LwdaPC4xOzyQbWGGoWsChlD/QuFZDqU1g89H+Knq4Rd/u/lmaHJxuj/uQNljxN95A9iyLGaM1R8GTfsp+18deJtgZjUvFeYZwrARtO24JNaVmzsAWnB07bDiA2+Nwu6dLvfwFls6jcllpNq3zs74lnBeup5TML9tPVvnbyoWRws8oZb2d1+ON7VmfkANzO1H9I/kUjhlK0DFL0v9JB7DhxlzqtXQetXiDbxuMbaIEGcgDy0Ay7IUL4Ln0uWfboO4YuS5Ufj31DTfR0vh1EsFdigxeOdBvhikm0RwNheo/wZsveMkWKFLHYIvSaK9l2BBR6Lm0OABxt44MJzJQ9bhFoSqzaQuKg82xybM3vBl3rEZRJhf5cZiyV9CafNKvxrqkme4mW5McAMI4/LrGuyKznl12ucUDBJ24CmkhjU=
