sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '8'
- '10'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '0.8'
  - node_js: '0.10'
  - node_js: '0.12'
  - node_js: '4'
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: dMqFUpV786JnQHl3hgwnoBLMAJu69GJ++yMarltzlCZAbgpzEdu+nQtDVxICGBdtNfKTIaPYUDLBVENysJwAj3cTTbFI5psD+tiKUKIw00O9ozJdYlbxRFcnc0u7T7XLeEXHVtRT9XqwmL+Aqv/p48oTjEJb/2zFnPkPk7r/yFQUMRCi8jkpsrG52vYYcyW76pWcJNjHBQfShCz3tJp1oEu/i6/ZyL9K/Lig0ZAxw9ky1QjRv8y6yjRw1+Pkmt3/DAzmjskGQhLmcQU9mWchYTcIi3Ywqz+LxOSUIOckiE2o/ZGtMm3fUOiHDNf7kW3vMUcOHj0TRGF5r8gwSE4sEqFD983wKU3rC1GJha0nigXBvsEJ70uWSWbBpxT4pXjRbifGHOp5Ip1CwwKYaY95jFWkubEiLpgZAkjArcL2eSN/TN+xGCqmGNKfu5q9ES1ztUZEpadiF4MbcRUJ9h7Yfr6hB5Ra3QGpxshnH+xvdIJYdf3i/HkuFdAgfOHIRwYyTbI/N93yc0y/o9yQDAxY9lSyyntvk1oBLzvBJAb6zYFP6zGisMt62gFyEuwmr5DLYXdDJHq/AxVKFoEUm+JzMd+anfLuSGzwblIkNamv/hIKcCKu/bhcEcz6mo8NRGEEcqq41iJO80Jq/x4srkShbIDQH91v9GRQvCX9ZMkuvHw=
